fetch-in-react - Lindsay Jin
lindsay-jin/c0124-code-solutions pull request #106
Opened 2024-04-05 22:26 UTC by lindsay-jin

2024-04-05 22:34 UTC, RobertGardner requested changes
Nice, but get the error handling correct. See my Slack message.

2024-04-05 22:34 UTC, RobertGardner commented on fetch-in-react/my-app/src/UserDetails.tsx
> +        );
Check response.ok here.

2024-04-05 22:34 UTC, RobertGardner commented on fetch-in-react/my-app/src/Users.tsx
> +        );
Here, too.

2024-04-05 23:41 UTC, lindsay-jin commented on fetch-in-react/my-app/src/Users.tsx
> +        );
Changes have been updated. Thank you!

2024-04-08 20:38 UTC, RobertGardner approved these changes

2024-04-08 20:38 UTC, RobertGardner commented on fetch-in-react/my-app/src/Users.tsx
> +        setIsLoading(false);
With this here, you can delete it on line 35.

2024-04-08 23:44 UTC, merged