html-relative-links - Lindsay Jin
lindsay-jin/c0124-code-solutions pull request #22
Opened 2024-02-05 23:22 UTC by lindsay-jin

<img width="301" alt="Screen Shot 2024-02-05 at 3 16 52 PM" src="https://github.com/lindsay-jin/c0124-code-solutions/assets/95058247/f8541531-7cd6-40b3-94aa-6ad24d32debb">

2024-02-06 17:50 UTC, shawnkost requested changes
One small thing here Lindsay!

2024-02-06 17:50 UTC, shawnkost commented on html-relative-links/contact-us/contact-us.html
> +      <li><a href="//projects/projects.html">Projects</a></li>
This should be `../` rather than `//`

2024-02-06 18:53 UTC, lindsay-jin commented on html-relative-links/contact-us/contact-us.html
> +      <li><a href="//projects/projects.html">Projects</a></li>
thanks for catching that!

2024-02-06 19:04 UTC, merged

2024-03-19 00:18 UTC, RobertGardner reviewed
You merged this before it was Approved. Unfortunately, that messes up our LMS. Would you be able to make a trivial change, commit it, the create a new PR for me to approve? That will clean up LMS. Thanks!