typescript-timers - Lindsay Jin
lindsay-jin/c0124-code-solutions pull request #54
Opened 2024-02-26 20:17 UTC by lindsay-jin

![Kapture 2024-02-26 at 12 10 43](https://github.com/lindsay-jin/c0124-code-solutions/assets/95058247/6c36137d-bd87-4734-a96b-aebae3f4e011)
![Kapture 2024-02-26 at 12 08 12](https://github.com/lindsay-jin/c0124-code-solutions/assets/95058247/d334d37b-b12d-4cc6-a2bc-40c713b1cc98)

2024-02-26 20:19 UTC, shawnkost requested changes
Looking good Lindsay! Just a couple tweaks here

2024-02-26 20:19 UTC, shawnkost commented on typescript-timers/interval.ts
> +}
Need to call `clearInterval` inside of here

2024-02-26 20:19 UTC, shawnkost commented on typescript-timers/timeout.ts
> +$h1.textContent = 'Hello There';
Delete this, we only want this to run inside our `setTimeout`

2024-02-28 02:30 UTC, lindsay-jin commented
Edits updated!

2024-03-18 15:02 UTC, shawnkost approved these changes
👍🏻

2024-03-25 05:02 UTC, merged